# Generated by Django 5.0 on 2023-12-06 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forneceddor', models.CharField(max_length=250)),
                ('tipoFornecedor', models.CharField(choices=[('Doador', 'Doador'), ('Fornecedor', 'Fornecedor')], max_length=10)),
                ('tempo', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=200)),
                ('qtd', models.PositiveIntegerField(default=0)),
                ('validade', models.DateField()),
                ('entrada', models.DateField(auto_now_add=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos_categoria', to='ABSJ.categoria')),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos_fornecedor', to='ABSJ.fornecedor')),
            ],
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='ABSJ.produto'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='ABSJ.produto'),
        ),
    ]
