# Generated by Django 5.0 on 2023-12-19 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Contribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribuidor', models.CharField(max_length=250, unique=True)),
                ('tipocontribuidor', models.CharField(choices=[('Doador', 'Doador'), ('Fornecedor', 'Fornecedor')], max_length=10)),
                ('tempo', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['tempo'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=200, unique=True)),
                ('qtd', models.PositiveIntegerField(default=0)),
                ('validade', models.DateField()),
                ('entrada', models.DateField(auto_now_add=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABSJ.categoria')),
                ('contribuidor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABSJ.contribuidor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['produto'],
            },
        ),
    ]
