# Generated by Django 5.0 on 2023-12-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['categoria']},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='category',
            new_name='categoria',
        ),
    ]
