# Generated by Django 5.0 on 2023-12-06 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='produto',
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABSJ.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ABSJ.fornecedor'),
        ),
    ]
