# Generated by Django 5.0 on 2023-12-22 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0002_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuidor',
            name='quantidade_dias',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
