# Generated by Django 5.0 on 2023-12-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0003_contribuidor_quantidade_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuidor',
            name='quantidade_dias',
            field=models.IntegerField(),
        ),
    ]
