# Generated by Django 5.0 on 2023-12-22 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0006_alter_contribuidor_quantidade_dias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='qtd',
            new_name='estoque',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='entrada',
        ),
        migrations.AlterField(
            model_name='contribuidor',
            name='quantidade_dias',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=7)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ABSJ.produto')),
            ],
        ),
    ]
