# Generated by Django 5.0 on 2023-12-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0008_movimento_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimento',
            name='data',
        ),
        migrations.AddField(
            model_name='movimento',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
