# Generated by Django 5.0 on 2023-12-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0009_remove_movimento_data_movimento_modificado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimento',
            options={'ordering': ['-modificado']},
        ),
        migrations.AlterField(
            model_name='contribuidor',
            name='quantidade_dias',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
