# Generated by Django 5.0 on 2023-12-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0011_compensacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compensacao',
        ),
    ]
