# Generated by Django 5.0 on 2023-12-24 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0013_compensacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuidor',
            name='tempo_ultima_atualizacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='Compensacao',
        ),
    ]
