# Generated by Django 5.0 on 2023-12-24 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0014_contribuidor_tempo_ultima_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.PositiveIntegerField(default=1, unique=True, validators=[django.core.validators.MaxValueValidator(13)]),
            preserve_default=False,
        ),
    ]
