# Generated by Django 5.0 on 2023-12-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0015_produto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
