# Generated by Django 5.0 on 2023-12-24 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0017_alter_produto_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuidor',
            name='tempo_ultima_atualizacao',
        ),
    ]
