# Generated by Django 5.0 on 2023-12-24 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0019_contribuidor_tempo_ultima_atualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_dias',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='tempo_ultima_atualizacao',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
