# Generated by Django 5.0 on 2023-12-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0020_produto_quantidade_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade_dias',
            field=models.IntegerField(default=0),
        ),
    ]
