# Generated by Django 5.0 on 2023-12-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0021_alter_produto_quantidade_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='id_name',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
