# Generated by Django 5.0 on 2023-12-31 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0022_produto_id_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='id_name',
            new_name='slug',
        ),
    ]
