# Generated by Django 5.0 on 2023-12-31 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0023_rename_id_name_produto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='slug',
        ),
    ]
