# Generated by Django 5.0 on 2023-12-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABSJ', '0025_produto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='contribuidor',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
